name: Build and test
run-name: Build and test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/farrimwildaxe/gitea-rust:1.96-slim-trixie
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: |
          cargo build
      - name: Test
        run: |
          cargo test
